version: '3'
services:
  db:
    container_name: pgdb
    image: postgres:latest
    volumes: 
      - C:\Users\Kass\Documents\pg_data/data:/var/lib/postgresql/data/pgdata
    restart: always
    ports: 
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: loteria_api

  webapps:
    image: tomcat:8.0-jre8-alpine
    volumes:
      - .\tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
      - .\popula-resultados\target\popula-resultados-0.0.1-SNAPSHOT.war:/usr/local/tomcat/webapps/popula.war
      - .\analise-lotofacil\target\analise-lotofacil-0.0.1-SNAPSHOT.war:/usr/local/tomcat/webapps/analise.war
    ports: 
      - '80:8080'
    command: ["catalina.sh", "run"]